# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [ ]:
import numpy as np
import itertools

def sign(permutation):
    """
    The function calculates a sign for given permutation
    """
    s = 0
    for i in range(len(permutation) - 1):
        for j in range(i + 1, len(permutation)):
            if permutation[i] > permutation[j]:
                s += 1
    if s % 2 == 0:
        return 1
    else:
        return -1

def calc_element(matrix, permutation):
    """
    The function calculates an addend that looks like the sign multiplied by product of n matrix elements
    """
    prod = sign(permutation)
    for i in range(len(matrix)):
        prod *= matrix[i][permutation[i]]
    return prod

def calc_determinant(matrix):
    """
    The function calculates determinant for given matrix
    """
    permutations = itertools.permutations(range(len(matrix)))
    s = 0
    for permutation in permutations:
        s += calc_element(matrix, permutation)
    return s

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

dim = input("Enter dimension size: ")
try:
    dim = int(dim)
    if dim < 1:
        raise ValueError
    matrix = random_matrix(dim)
    print("Matrix:")
    print(matrix)
    print(f"Determinant is {calc_determinant(matrix)}")
except:
    print("Dimension size must be a positive integer")

Matrix:
[[1 9 5 4 3 4 3 3 8 9]
 [1 4 3 1 9 7 1 2 7 8]
 [8 0 7 3 3 9 7 6 9 1]
 [1 8 3 7 8 8 0 4 4 7]
 [7 6 8 0 6 9 5 5 5 0]
 [0 8 3 9 6 7 3 9 0 6]
 [2 7 4 5 8 6 6 3 8 0]
 [7 9 7 8 7 0 2 9 1 5]
 [3 3 5 4 3 1 5 1 6 9]
 [5 6 8 1 5 6 3 5 5 2]]
Determinant is 253358606
